import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/header";
import Sidebar from "@/components/Sidebar";
import PageWrapper from "@/components/page-wrapper";
import MarginWidthWrapper from "@/components/margin-width-wrapper";
import Login from "./login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const loggenIn = true

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar/> */}
        <div className="flex">
          {loggenIn ? (
            <>
          <Sidebar/>
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header/>
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
          </>
          ) : (<Login/>)}
        </div>
      </body>
    </html>
  );
}
