import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/Sidebar";
import PageWrapper from "@/components/page-wrapper";
import MarginWidthWrapper from "@/components/margin-width-wrapper";
import Login from "./(pages)/login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ETF Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className} style={{overflow: 'hidden'}}>
        <div className="flex">
          {process.env.LOGGED_IN === "true" ? (
            <>
          <Sidebar/>
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header/>
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
          </>
          ) : (<Login/>)}
        </div>
      </body>
    </html>
  );
}
